version: '3.8'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    restart: always
    container_name: flask_app
    volumes:
      - ./gcp-key.json:/key.json
    environment:
      - GCS_BUCKET=shortened-urls-bucket
      - GOOGLE_APPLICATION_CREDENTIALS=/key.json
    networks:
      - shared_network

networks:
  shared_network:
    external: true
